### ISSUE TITLE
[bartomeus_2005] Networks are missing

### ISSUE THREAD

**Issue by SteveViss** [mangal-interactions/mangal-datasets#18]
We need to investigate this.

**Comment by BenMerSci** [comment]
https://github.com/mangal-wg/mangal-datasets/blob/03f6c8cc9519aa710f9d5cda8b12369e5ab41ebe/Bartomeus_2005/injection_CapCreus.r#L275-L300

**Comment by BenMerSci** [comment]
Resolved. Networks, nodes and interactions uploaded by @tpoisot.
